// Generated by kit-u1 | ai-guided strategy | 2026-03-09
// ⚠️  Locators are AI-inferred — verify selectors.json before running in CI
// Test Case: TC-01 — Successful Login (Happy Path)
// Pages: LoginPage -> SecureAreaPage

import { test, expect } from '@playwright/test';
import { LoginPage }      from '@pages/LoginPage';
import { SecureAreaPage } from '@pages/SecureAreaPage';

// Test data — move to an environment-specific fixture or .env for CI
const validUser = {
  username: 'practice',
  password: 'SuperSecretPassword!',
};

test.describe('Authentication', () => {

  test('TC-01: Successful Login (Happy Path)', { tag: '@smoke' }, async ({ page }) => {
    const loginPage      = new LoginPage(page);
    const secureAreaPage = new SecureAreaPage(page);

    // ── Page: LoginPage ────────────────────────────────────────────────────
    await test.step('Navigate to login page', async () => {
      await loginPage.navigate();
    });

    await test.step('Enter valid credentials', async () => {
      await loginPage.login(validUser.username, validUser.password);
    });

    // transitionTo: SecureAreaPage
    await test.step('Wait for secure area navigation', async () => {
      await page.waitForURL(/\/secure/);
    });

    // ── Page: SecureAreaPage ───────────────────────────────────────────────
    await test.step('Verify URL is the secure area', async () => {
      await expect(page).toHaveURL(/\/secure/);
    });

    await test.step('Verify success message contains "Logged in as"', async () => {
      await expect(secureAreaPage.loggedInMessage).toBeVisible();
    });

    await test.step('Verify no validation error is displayed', async () => {
      await expect(loginPage.flashMessage).not.toHaveClass(/error/);
    });
  });

});
