// Generated by kit-u1 | dom-based strategy | 2026-03-09
// Test Case: TC_AMZ_001 — Verify user can search for a product
// Pages: AmazonHomePage -> AmazonSearchPage

import { test, expect } from '@playwright/test';
import { AmazonHomePage }   from '@pages/AmazonHomePage';
import { AmazonSearchPage } from '@pages/AmazonSearchPage';

test.describe('Amazon Product Search', () => {

  test('TC_AMZ_001: Verify user can search for a product', { tag: '@smoke' }, async ({ page }) => {
    const amazonHomePage   = new AmazonHomePage(page);
    const amazonSearchPage = new AmazonSearchPage(page);

    // ── Page: AmazonHomePage ───────────────────────────────────────────────
    await test.step('Navigate to Amazon homepage', async () => {
      await amazonHomePage.navigate();
    });

    await test.step('Verify search bar is visible', async () => {
      await expect(amazonHomePage.searchInput).toBeVisible();
    });

    await test.step('Enter search query: iPhone', async () => {
      await amazonHomePage.fillSearch('iPhone');
    });

    // transitionTo: AmazonSearchPage
    await test.step('Click search button and wait for results page', async () => {
      await amazonHomePage.clickSearch();
      await page.waitForURL(/\/s\?/);
    });

    // ── Page: AmazonSearchPage ─────────────────────────────────────────────
    await test.step('Verify search results container is displayed', async () => {
      await expect(amazonSearchPage.resultsContainer).toBeVisible();
    });

    await test.step('Verify product listings related to iPhone are shown', async () => {
      await expect(amazonSearchPage.productItems.first()).toBeVisible();
      const count = await amazonSearchPage.getProductCount();
      expect(count).toBeGreaterThan(0);
    });
  });

});
