// Generated by kit-u1 | dom-based strategy | 2026-03-09
// Source DOM: snapshots/amazonHome-page.html
// DO NOT add assertions here — assertions belong in spec files only.

import { Page } from '@playwright/test';

export class AmazonHomePage {
  // ─── Locators ─────────────────────────────────────────────────────────────
  readonly searchInput      = this.page.getByRole('searchbox', { name: 'Search Amazon.in' });
  readonly searchButton     = this.page.locator('#nav-search-submit-button');
  readonly categoryDropdown = this.page.locator('#searchDropdownBox');

  constructor(private readonly page: Page) {}

  // ─── Navigation ───────────────────────────────────────────────────────────
  async navigate(): Promise<void> {
    await this.page.goto('https://www.amazon.in/');
  }

  // ─── Actions ──────────────────────────────────────────────────────────────
  async fillSearch(query: string): Promise<void> {
    await this.searchInput.fill(query);
  }

  async clickSearch(): Promise<void> {
    await this.searchButton.click();
  }

  async selectCategory(category: string): Promise<void> {
    await this.categoryDropdown.selectOption({ label: category });
  }

  // ─── Composite Actions ────────────────────────────────────────────────────
  async searchFor(query: string): Promise<void> {
    await this.fillSearch(query);
    await this.clickSearch();
  }
}
