// Generated by kit-u1 | dom-based strategy | 2026-03-09
// Source DOM: snapshots/amazonSearch-page.html
// DO NOT add assertions here — assertions belong in spec files only.

import { Page, Locator } from '@playwright/test';

export class AmazonSearchPage {
  // ─── Locators ─────────────────────────────────────────────────────────────
  readonly resultsContainer = this.page.locator("[data-component-type='s-search-results']");
  readonly productItems     = this.page.locator("div[role='listitem'][data-asin]");
  readonly productTitle     = this.page.locator("div[data-asin] h2 span");
  readonly resultsHeader    = this.page.locator('.s-breadcrumb-header-text h2');

  constructor(private readonly page: Page) {}

  // ─── Actions ──────────────────────────────────────────────────────────────
  async getProductCount(): Promise<number> {
    return this.productItems.count();
  }

  async getResultsHeaderText(): Promise<string> {
    return this.resultsHeader.innerText();
  }

  async getProductTitleAt(index: number): Promise<string> {
    return this.productItems.nth(index).locator('h2 span').innerText();
  }

  async clickProductAt(index: number): Promise<void> {
    await this.productItems.nth(index).locator('h2 a').click();
  }
}
