// Generated by kit-u1 | ai-guided strategy | 2026-03-09
// ⚠️  Locators are AI-inferred — verify against https://practice.expandtesting.com/login
// DO NOT add assertions here — assertions belong in spec files only.

import { Page } from '@playwright/test';

export class LoginPage {
  // ─── Locators ─────────────────────────────────────────────────────────────
  readonly usernameInput = this.page.getByLabel('Username');
  readonly passwordInput = this.page.getByLabel('Password');
  readonly loginButton   = this.page.getByRole('button', { name: 'Login' });
  readonly flashMessage  = this.page.locator('#flash');

  constructor(private readonly page: Page) {}

  // ─── Navigation ───────────────────────────────────────────────────────────
  async navigate(): Promise<void> {
    await this.page.goto('/login');
  }

  // ─── Actions ──────────────────────────────────────────────────────────────
  async fillUsername(username: string): Promise<void> {
    await this.usernameInput.fill(username);
  }

  async fillPassword(password: string): Promise<void> {
    await this.passwordInput.fill(password);
  }

  async clickLogin(): Promise<void> {
    await this.loginButton.click();
  }

  // ─── Composite Actions ────────────────────────────────────────────────────
  async login(username: string, password: string): Promise<void> {
    await this.fillUsername(username);
    await this.fillPassword(password);
    await this.clickLogin();
  }
}
