// Generated by kit-u1 | ai-guided strategy | 2026-03-09
// ⚠️  Locators are AI-inferred — verify against https://practice.expandtesting.com/secure
// DO NOT add assertions here — assertions belong in spec files only.

import { Page } from '@playwright/test';

export class SecureAreaPage {
  // ─── Locators ─────────────────────────────────────────────────────────────
  readonly successBanner    = this.page.locator('#flash.success');
  readonly loggedInMessage  = this.page.getByText('Logged in as');
  readonly logoutButton     = this.page.getByRole('link', { name: 'Logout' });

  constructor(private readonly page: Page) {}

  // ─── Actions ──────────────────────────────────────────────────────────────
  async clickLogout(): Promise<void> {
    await this.logoutButton.click();
  }

  async getSuccessBannerText(): Promise<string> {
    return this.successBanner.innerText();
  }
}
