// Generated by automation-kit | Kit: kit-u1
import { test as base } from '@playwright/test';

type AuthFixtures = {
  authenticatedPage: import('@playwright/test').Page;
};

export const test = base.extend<AuthFixtures>({
  authenticatedPage: async ({ page }, use) => {
    // TODO: Add your authentication setup here
    // e.g., await page.goto('/login'); await loginPage.login(email, pass);
    await use(page);
  },
});

export { expect } from '@playwright/test';
